# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# syntax=docker/dockerfile:1
FROM python:3.10-bullseye


RUN apt-get update && \
apt-get install -y --no-install-recommends \
curl \
unzip \
openssh-server \
sudo \
openjdk-11-jdk && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

# Optional env variables
ENV SPARK_HOME=${SPARK_HOME:-"/opt/spark"}
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip:$PYTHONPATH

RUN useradd --uid 1001 --create-home --shell /bin/bash --user-group me && \
echo 'me:changeme' | chpasswd && \
echo 'me ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/me

ENV SPARK_HOME=${SPARK_HOME:-"/opt/spark"}
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip:$PYTHONPATH
WORKDIR ${SPARK_HOME}

USER root
RUN chown -R me:me /home
RUN chown -R me:me $SPARK_HOME
USER me

ENV SPARK_VERSION=3.5.2
ENV SPARK_MAJOR_VERSION=3.5
ENV ICEBERG_VERSION=1.5.2

# Download spark
RUN mkdir -p ${SPARK_HOME} \
 && curl https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz -o spark-${SPARK_VERSION}-bin-hadoop3.tgz \
 && tar xvzf spark-${SPARK_VERSION}-bin-hadoop3.tgz --directory /opt/spark --strip-components 1 \
 && rm -rf spark-${SPARK_VERSION}-bin-hadoop3.tgz

# Download iceberg spark runtime and AWS bundle
RUN curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar -Lo /opt/spark/jars/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar
RUN curl -s https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/${ICEBERG_VERSION}/iceberg-aws-bundle-${ICEBERG_VERSION}.jar -Lo /opt/spark/jars/iceberg-aws-bundle-${ICEBERG_VERSION}.jar

# Download nessi package
RUN curl -o ${SPARK_HOME}/jars/nessie-spark-extensions-3.5_2.12-0.94.4.jar https://repo1.maven.org/maven2/org/projectnessie/nessie-integrations/nessie-spark-extensions-3.5_2.12/0.94.4/nessie-spark-extensions-3.5_2.12-0.94.4.jar

# get suitable hadoop-aws version via this link: https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws
# Download AWS bundles to interact and manage minio objects via spark (without using iceberg)
ENV HADOOP_AWS_VERSION=3.3.4
RUN curl -o ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar
RUN curl -o ${SPARK_HOME}/jars/aws-java-sdk-bundle-1.12.769.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.769/aws-java-sdk-bundle-1.12.769.jar


RUN mkdir -p /home/iceberg/localwarehouse 
RUN mkdir -p /home/iceberg/warehouse /home/iceberg/spark-events /home/iceberg

ENV PATH="/opt/spark/sbin:/opt/spark/bin:${PATH}"

RUN chmod u+x /opt/spark/sbin/* && \
    chmod u+x /opt/spark/bin/*

COPY dockerfiles/spark/entrypoint.sh .
USER root
RUN chmod +x $SPARK_HOME/entrypoint.sh
USER me
COPY dockerfiles/spark/requirements.txt .
RUN pip install -r requirements.txt
ENTRYPOINT ["./entrypoint.sh"]