FROM apache/airflow:2.10.1

COPY ./requirements.txt .

RUN python3 -m pip install --upgrade pip \
&& pip install -r ./requirements.txt

COPY ./profiles.yml /home/airflow/.dbt/profiles.yml

USER airflow