amazon_orders:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: "{{ env_var('NESSIE_CATALOG_NAME') }}.{{ env_var('GOLD_NAMESPACE') }}"
      host: spark
      port: 10000